#!/usr/bin/env bash

npx @bookshop/generate

if [[ $TRANSLATE == "true" ]];
then
  echo "Installing Rosey"
  npm install

  echo "Translating site with Rosey"   
  npx rosey@latest build --source dist --dest translated_site
fi