#!/usr/bin/env bash

npx @bookshop/generate
# Add an env variable of SYNC_PATHS=rosey/locales for this to work on CloudCannon
node src/assets/js/generateLocales.mjs

if [[ $TRANSLATE == "true" ]];
then
  echo "Installing Rosey"
  npm install

  echo "Translating site with Rosey"
  # There's a little bit of shuffling around here to ensure the translated site ends up where CloudCannon picks up your site
  mv ./dist ./_untranslated_site
  npx rosey@latest build --source _untranslated_site --dest dist
fi